version: "3.8"

services:
  app:
    image: img-app-contenerizada
    build: 
      context: .
      dockerfile: Dockerfile.yml  # Asegúrate de que este es el nombre correcto del archivo Dockerfile
    ports:
      - "5054:5054"  # Esto mapea el puerto 5054 en tu máquina local al puerto 5054 en el contenedor
    volumes:
      - ./dotnet_contenerized:/app
    container_name: c_docker_contenerized
