version: "3.8"

services:
  app:
    image: alex-dotnet-img
    build: 
      context: .
      dockerfile: Dockerfile.yml
    ports:
      - "5054:5054"
    volumes:
      - ./dotnet_contenerized:/app
    command: ["watch", "run", "--urls", "http://+:5054"]
    container_name: alex-dotnet-container

